# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180807_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shuxue',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='yuwen',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
