# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180807_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField()),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
