# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_myuser_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
