# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'promission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=30)),
                ('r_p', models.ManyToManyField(to='app.Promission')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='r',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Role'),
        ),
    ]
