# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
            options={
                'db_table': 'stu_info',
            },
        ),
        migrations.RemoveField(
            model_name='grade',
            name='stu',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
