# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0005_auto_20180814_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='r_u',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backweb.User'),
        ),
    ]
