# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=10, unique=True)),
                ('g_crate_time', models.DateTimeField(auto_now_add=True)),
                ('g_modify_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10, unique=True)),
                ('s_create_time', models.DateTimeField(auto_now_add=True)),
                ('s_sex', models.BooleanField(default=1)),
                ('img', models.ImageField(null=True, upload_to='upload')),
                ('is_del', models.BooleanField(default=0)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Grade')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
