# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181128_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=10)),
                ('stu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
